#define BAR_ALPHA_CONSTS \
	static const unsigned int baralpha = 0xd0; \
	static const unsigned int borderalpha = OPAQUE;
#define BAR_ALPHA_ARRAY \
	static const unsigned int alphas[][3] = { \
		/*                       fg      bg        border     */ \
		[SchemeNorm]         = { OPAQUE, baralpha, borderalpha }, \
		[SchemeSel]          = { OPAQUE, baralpha, borderalpha }, \
		[SchemeTitleNorm]    = { OPAQUE, baralpha, borderalpha }, \
		[SchemeTitleSel]     = { OPAQUE, baralpha, borderalpha }, \
		[SchemeTagsNorm]     = { OPAQUE, baralpha, borderalpha }, \
		[SchemeTagsSel]      = { OPAQUE, baralpha, borderalpha }, \
		[SchemeHidNorm]      = { OPAQUE, baralpha, borderalpha }, \
		[SchemeHidSel]       = { OPAQUE, baralpha, borderalpha }, \
		[SchemeUrg]          = { OPAQUE, baralpha, borderalpha }, \
		[SchemeLtSymbol]     = { OPAQUE, baralpha, borderalpha }, \
		[SchemeScratchSel]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeScratchNorm] = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexActTTB]   = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexActLTR]   = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexActMONO]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexActGRID]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexActGRD1]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexActGRD2]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexActGRDM]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexActHGRD]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexActDWDL]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexActSPRL]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexActFloat] = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexInaTTB]   = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexInaLTR]   = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexInaMONO]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexInaGRID]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexInaGRD1]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexInaGRD2]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexInaGRDM]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexInaHGRD]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexInaDWDL]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexInaSPRL]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexInaFloat] = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexSelTTB]   = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexSelLTR]   = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexSelMONO]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexSelGRID]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexSelGRD1]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexSelGRD2]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexSelGRDM]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexSelHGRD]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexSelDWDL]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexSelSPRL]  = { OPAQUE, baralpha, borderalpha }, \
		[SchemeFlexSelFloat] = { OPAQUE, baralpha, borderalpha }, \
	};
